---
- hosts: localhost
  connection: local 
  tasks:
  - name: start an instance with a public IP address
    amazon.aws.ec2_instance:
      name: "{{ item.name }}"
      key_name: "Ansible-Key"
      # vpc_subnet_id: subnet-5ca1ab1e
      instance_type: t2.micro
      security_group: default
      region: us-east-1
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      network:
        assign_public_ip: true
      image_id: "{{ item.image }}"
      tags:
        environment: "{{ item.name }}"
    loop:
      - {image: "ami-0ae8f15ae66fe8cda",name: node-1}
      - {image: "ami-04a81a99f5ec58529",name: node-2}
      - {image: "ami-04a81a99f5ec58529",name: node-3}

